x-environment: &default-environment
  ROUSSELTM_ENV: prod
  ROUSSELTM_APP: projet1
  DT_LOCALTOVIRTUALHOSTNAME: projet1
  DT_CUSTOM_PROP: "rousseltm_app=projet1"
  
services:
     
  nginx-projet1:
    image: nginx
    restart: always
    volumes:
      - ./nginx/prod:/etc/nginx/conf.d
      - ./sources/projet1:/usr/share/nginx/html
    environment: 
      << : [*default-environment]
    deploy:
      replicas: 1
    networks:
      - frontend
    ports:
      - "88:80"

  php-projet1:
    image: lekpamartin/php-fpm-redis
    restart: always
    volumes:
      - ./sources/projet1:/usr/share/nginx/html
    environment: 
      << : [*default-environment]
    deploy:
      replicas: 1
    networks:
      - frontend
      - backend


  redis-projet1:
    image: redis/redis-stack
    restart: always
    volumes:
      - redis_data:/data
      - ./redis/conf:/usr/local/etc/redis
    environment:
      << : [*default-environment]
    networks:
      - backend


networks:
  frontend:
  backend:
    
volumes:
  redisinsight_data:
  redis_data: